config/routes.rb
Flashcard::Application.routes.draw do
#  get "/decks" => "decks#index"
#  get "/decks/new" => "decks#new"
#  get "/decks/:id" => "decks#show", as: :deck
#  post "/decks" => "decks#create"
#  get "/decks/:id/edit" => "decks#edit"
#  put "/decks/:id" => "decks#update"
#  delete "/decks/:id" => "decks#destroy"
  root to: "home#index"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :decks do
    resources :cards, except: :index
  end


end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck #deck, deck=
  attr_accessible :back, :front
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards
  belongs_to :user
  attr_accessible :name #allows us to do mass-assignment for 'name' of new decks
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :decks
  attr_accessible :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
  	if cookies[:user_id]
  	  user_id = cookies.signed[:user_id]
  	  @current_user = User.find_by_id(user_id)
  	end
  end
  helper_method :current_user

  def sign_in user
  	cookies.signed[:user_id] = user.id
  end

  def authenticate
  	if !signed_in?
  	redirect_to new_session_path
    end
  end

  def signed_in?
  	current_user # nil or #<User>
  end
  helper_method :signed_in?
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
  	@deck = find_deck
  	@card = find_card(@deck)
  end

  def new
  	@deck = find_deck
  	@card = @deck.cards.new
  end

  def create 
  	@deck = find_deck
  	@card = @deck.cards.new(params[:card])
  	@card.save
  	redirect_to @deck
  end

  def edit
  	@deck = find_deck
  	@card = find_card(@deck)
  end

  def update
  	@deck = find_deck
  	@card = find_card(@deck)
  	@card.update_attributes(params[:card])
  	redirect_to @deck
  end

  def destroy
  	@deck = find_deck
  	@card = find_card(@deck)
  	@card.destroy
  	redirect_to @deck
  end


  private 

  def find_deck
  	Deck.find(params[:deck_id])
  end

  def find_card deck
  	deck.cards.find(params[:id])
  end  

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :authenticate
  
  def index
  	@decks = current_user.decks # Instance variables in controllers --> instance variables in view
  end

  def show
  	@deck = Deck.find(params[:id])
    @cards = @deck.cards
  end

  def new
  	@deck = Deck.new
  end

  def create
    @deck = current_user.decks.new(params[:deck])
  	#@deck = Deck.new(params[:deck]) # Why isn't the arg inside the params hash with indifferent access ":name" instead of ":deck"?
  	@deck.save
  	redirect_to decks_path
  end

  def edit
  	@deck = Deck.find(params[:id])
  end

  def update
  	@deck = Deck.find(params[:id])
  	@deck.update_attributes(params[:deck])
  	redirect_to @deck
  end

  def destroy
  	@deck = Deck.find(params[:id])
  	@deck.destroy
  	redirect_to decks_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
 
  def create
    puts params
  	user = User.find_by_email(params[:session][:email])
  	if user.nil?
  	  redirect_to root_path
  	else
      	sign_in(user)
      	cookies.signed[:user_id] = user.id
      	redirect_to decks_path
    end
  end

  def destroy
  	cookies.delete(:user_id)
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user  = User.new
  end

  def create
  	@user = User.new(params[:user])
  	@user.save
  	sign_in @user
  	redirect_to  decks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
  <div>
  	<%= form.label :front %>
  	<%= form.text_field :front %>
  </div>
  <div>
  	<%= form.label :back %>
  	<%= form.text_field :back %>
  </div>
    

app/views/cards/edit.html.erb
<%= form_for([@deck, @card]) do |form| %>
  <%= render form %>  
  <%= form.submit "Update card" %>
<% end %>

app/views/cards/new.html.erb
<%= form_for([@deck, @card]) do |form| %>
  <%= render form %>
  <%= form.submit "Create card" %>
<% end %>

app/views/cards/show.html.erb
<%= link_to @deck.name, @deck %>
<div><%= @card.front %></div>
<div><%= @card.back %></div>

app/views/decks/edit.html.erb
<%= form_for(@deck) do |form|%>
  <div>
  	<%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <%= form.submit "Update deck" %>
<% end %>

app/views/decks/index.html.erb
<h3>Welcome</h3>

<%= link_to "Add New Deck", new_deck_path %>

<% @decks.each do |deck| %>
  <div>
  	<%= link_to deck.name, deck %>
  	-
  	<%= link_to "Edit", edit_deck_path(deck) %>
  	<%= link_to "Delete", deck, method: :delete, confirm: "Are you sure?" %>
  </div>
<% end %>

app/views/decks/new.html.erb
<%= form_for(@deck) do |form|%>
  <div>
  	<%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <%= form.submit "Create deck" %>
<% end %>

app/views/decks/show.html.erb
<%= link_to "Decks", decks_path %>
<h2><%= @deck.name %></h2>

<%= link_to "New card", new_deck_card_path(@deck) %>
<% @cards.each do |card| %>
  <div>
  	<%= link_to card.front, [@deck, card] %>
  	-
  	<%= link_to "Edit", edit_deck_card_path(@deck,card) %>
  	<%= link_to "Delete", [@deck, card], method: :delete, confirm: "Are you sure?" %>
  </div>
<% end %>

app/views/home/index.html.erb
Welcome to the languages Flashcard app!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcard</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
    <% if signed_in? %>
      Welcome <%= current_user.email %>
      <%= link_to "Sign out", session_path, method: :delete %>
    <% else %>
      <%= link_to "Log in", new_session_path %>
      <%= link_to "Sign up", new_user_path %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for (@user) do |form| %>
  <div>
  	<%= form.label :email %>
  	<%= form.text_field :email %>
  </div>
  <%= form.submit "Sign up" %>
<% end %>